[env:nologo_esp32c3_super_mini]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = nologo_esp32c3_super_mini
board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_build.f_flash = 40000000L
upload_speed = 460800
monitor_speed = 115200
upload_flags = --no-stub
build_flags = 
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = post:scripts/merge_bin.py
lib_ldf_mode = chain
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    tzapu/WiFiManager @ ^2.0.16-rc.2
    bitbank2/PNGdec @ ^1.0.1
    bblanchon/ArduinoJson @ ^7.0.0