[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

# Pridaný riadok pre spustenie skriptu po builde
extra_scripts = post:merge_bin.py

lib_deps =
  lovyan03/LovyanGFX@^1.2.7
  bitbank2/PNGdec@^1.1.3
  tzapu/WiFiManager@^2.0.17

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

build_flags =
  -DCORE_DEBUG_LEVEL=3